"""init

Revision ID: 02da7c79e7cb
Revises: c20f3f21c019
Create Date: 2025-11-28 15:53:08.784124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02da7c79e7cb'
down_revision: Union[str, Sequence[str], None] = 'c20f3f21c019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_bik', sa.String(length=50), nullable=True),
    sa.Column('bank_cor_name', sa.String(length=255), nullable=True),
    sa.Column('bank_cor_bik', sa.String(length=50), nullable=True),
    sa.Column('bank_cor_acc', sa.String(length=50), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_account_id'), 'bank_account', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_account_id'), table_name='bank_account')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
