"""init

Revision ID: 2ec0773c2d61
Revises: 3fc1fe1c7976
Create Date: 2025-11-28 15:22:56.764757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec0773c2d61'
down_revision: Union[str, Sequence[str], None] = '3fc1fe1c7976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etsng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('code_gng', sa.String(length=15), nullable=False),
    sa.Column('mvrn', sa.Integer(), nullable=True),
    sa.Column('cargo_class', sa.Integer(), nullable=True),
    sa.Column('danger', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsng_id'), 'etsng', ['id'], unique=False)
    op.create_table('gng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('code_etsng', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gng_id'), 'gng', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gng_id'), table_name='gng')
    op.drop_table('gng')
    op.drop_index(op.f('ix_etsng_id'), table_name='etsng')
    op.drop_table('etsng')
    # ### end Alembic commands ###
