"""init

Revision ID: 50a4a5a87b2c
Revises: f78c1fe0e582
Create Date: 2025-11-28 12:47:25.495756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a4a5a87b2c'
down_revision: Union[str, Sequence[str], None] = 'f78c1fe0e582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wagon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wagon_type_id'), 'wagon_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wagon_type_id'), table_name='wagon_type')
    op.drop_table('wagon_type')
    # ### end Alembic commands ###
