"""init

Revision ID: 5d00e2193fb7
Revises: 02da7c79e7cb
Create Date: 2025-11-28 16:09:58.021157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d00e2193fb7'
down_revision: Union[str, Sequence[str], None] = '02da7c79e7cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railway_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('is_transit', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('first_number', sa.Integer(), nullable=True),
    sa.Column('is_one_code', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_code_id'), 'railway_code', ['id'], unique=False)
    op.create_table('railway_subcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_subcode_id'), 'railway_subcode', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_railway_subcode_id'), table_name='railway_subcode')
    op.drop_table('railway_subcode')
    op.drop_index(op.f('ix_railway_code_id'), table_name='railway_code')
    op.drop_table('railway_code')
    # ### end Alembic commands ###
