"""init

Revision ID: 5fc32d3461eb
Revises: 
Create Date: 2025-12-02 17:38:40.606535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fc32d3461eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code_iso', sa.String(length=3), nullable=False),
    sa.Column('code_alpha2', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_code_alpha2'), 'country', ['code_alpha2'], unique=False)
    op.create_index(op.f('ix_country_code_iso'), 'country', ['code_iso'], unique=False)
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=False)
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=False)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=False)
    op.create_table('etsng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('code_gng', sa.String(length=15), nullable=False),
    sa.Column('mvrn', sa.Integer(), nullable=True),
    sa.Column('cargo_class', sa.Integer(), nullable=True),
    sa.Column('danger', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsng_code'), 'etsng', ['code'], unique=False)
    op.create_index(op.f('ix_etsng_id'), 'etsng', ['id'], unique=False)
    op.create_index(op.f('ix_etsng_name'), 'etsng', ['name'], unique=False)
    op.create_table('gng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('code_etsng', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gng_code'), 'gng', ['code'], unique=False)
    op.create_index(op.f('ix_gng_id'), 'gng', ['id'], unique=False)
    op.create_index(op.f('ix_gng_name'), 'gng', ['name'], unique=False)
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_index(op.f('ix_service_type_name'), 'service_type', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_id'), 'vat', ['id'], unique=False)
    op.create_index(op.f('ix_vat_name'), 'vat', ['name'], unique=False)
    op.create_table('wagon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wagon_type_id'), 'wagon_type', ['id'], unique=False)
    op.create_index(op.f('ix_wagon_type_name'), 'wagon_type', ['name'], unique=False)
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=25), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_bin_iin'), 'contractor', ['bin_iin'], unique=False)
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_name'), 'contractor', ['name'], unique=False)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_tariff', sa.Boolean(), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    op.create_index(op.f('ix_operation_name'), 'operation', ['name'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=25), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_bin_iin'), 'organization', ['bin_iin'], unique=False)
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('territory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territory_code'), 'territory', ['code'], unique=False)
    op.create_index(op.f('ix_territory_id'), 'territory', ['id'], unique=False)
    op.create_index(op.f('ix_territory_name'), 'territory', ['name'], unique=False)
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_bik', sa.String(length=50), nullable=True),
    sa.Column('bank_cor_name', sa.String(length=255), nullable=True),
    sa.Column('bank_cor_bik', sa.String(length=50), nullable=True),
    sa.Column('bank_cor_acc', sa.String(length=50), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_account_id'), 'bank_account', ['id'], unique=False)
    op.create_index(op.f('ix_bank_account_name'), 'bank_account', ['name'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=False)
    op.create_index(op.f('ix_contract_name'), 'contract', ['name'], unique=False)
    op.create_table('railway_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('is_transit', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('first_number', sa.Integer(), nullable=True),
    sa.Column('is_one_code', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_code_code'), 'railway_code', ['code'], unique=False)
    op.create_index(op.f('ix_railway_code_id'), 'railway_code', ['id'], unique=False)
    op.create_index(op.f('ix_railway_code_name'), 'railway_code', ['name'], unique=False)
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('paragraphs', sa.String(length=50), nullable=True),
    sa.Column('tech_pd', sa.String(length=100), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_code'), 'station', ['code'], unique=False)
    op.create_index(op.f('ix_station_id'), 'station', ['id'], unique=False)
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=False)
    op.create_table('railway_subcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['railway_code.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_subcode_id'), 'railway_subcode', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_railway_subcode_id'), table_name='railway_subcode')
    op.drop_table('railway_subcode')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_index(op.f('ix_station_id'), table_name='station')
    op.drop_index(op.f('ix_station_code'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_railway_code_name'), table_name='railway_code')
    op.drop_index(op.f('ix_railway_code_id'), table_name='railway_code')
    op.drop_index(op.f('ix_railway_code_code'), table_name='railway_code')
    op.drop_table('railway_code')
    op.drop_index(op.f('ix_contract_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_bank_account_name'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_id'), table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index(op.f('ix_territory_name'), table_name='territory')
    op.drop_index(op.f('ix_territory_id'), table_name='territory')
    op.drop_index(op.f('ix_territory_code'), table_name='territory')
    op.drop_table('territory')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_bin_iin'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_operation_name'), table_name='operation')
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    op.drop_index(op.f('ix_contractor_name'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_bin_iin'), table_name='contractor')
    op.drop_table('contractor')
    op.drop_index(op.f('ix_wagon_type_name'), table_name='wagon_type')
    op.drop_index(op.f('ix_wagon_type_id'), table_name='wagon_type')
    op.drop_table('wagon_type')
    op.drop_index(op.f('ix_vat_name'), table_name='vat')
    op.drop_index(op.f('ix_vat_id'), table_name='vat')
    op.drop_table('vat')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_type_name'), table_name='service_type')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.drop_index(op.f('ix_gng_name'), table_name='gng')
    op.drop_index(op.f('ix_gng_id'), table_name='gng')
    op.drop_index(op.f('ix_gng_code'), table_name='gng')
    op.drop_table('gng')
    op.drop_index(op.f('ix_etsng_name'), table_name='etsng')
    op.drop_index(op.f('ix_etsng_id'), table_name='etsng')
    op.drop_index(op.f('ix_etsng_code'), table_name='etsng')
    op.drop_table('etsng')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_index(op.f('ix_country_code_iso'), table_name='country')
    op.drop_index(op.f('ix_country_code_alpha2'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
