"""init

Revision ID: 79e5e626daf5
Revises: c93220d11462
Create Date: 2025-11-28 15:42:14.142495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e5e626daf5'
down_revision: Union[str, Sequence[str], None] = 'c93220d11462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=25), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_table('contractor')
    # ### end Alembic commands ###
