"""init

Revision ID: 82b2f7ec2d41
Revises: a8096446804d
Create Date: 2025-12-04 16:33:09.741836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82b2f7ec2d41'
down_revision: Union[str, Sequence[str], None] = 'a8096446804d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dislocation', sa.Column('container_type', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_dislocation_container_type'), 'dislocation', ['container_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dislocation_container_type'), table_name='dislocation')
    op.drop_column('dislocation', 'container_type')
    # ### end Alembic commands ###
