"""init

Revision ID: 8dde6b62f9f1
Revises: 0767a993a77b
Create Date: 2025-11-28 15:30:56.554365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dde6b62f9f1'
down_revision: Union[str, Sequence[str], None] = '0767a993a77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_tariff', sa.Boolean(), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    # ### end Alembic commands ###
