"""init

Revision ID: 8e90b4cdeb55
Revises: 
Create Date: 2025-12-05 22:17:25.136479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e90b4cdeb55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code_iso', sa.String(length=3), nullable=False),
    sa.Column('code_alpha2', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_code_alpha2'), 'country', ['code_alpha2'], unique=False)
    op.create_index(op.f('ix_country_code_iso'), 'country', ['code_iso'], unique=False)
    op.create_index(op.f('ix_country_id'), 'country', ['id'], unique=False)
    op.create_index(op.f('ix_country_name'), 'country', ['name'], unique=False)
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_code'), 'currency', ['code'], unique=False)
    op.create_index(op.f('ix_currency_id'), 'currency', ['id'], unique=False)
    op.create_index(op.f('ix_currency_name'), 'currency', ['name'], unique=False)
    op.create_table('etsng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('code_gng', sa.String(length=15), nullable=False),
    sa.Column('mvrn', sa.Integer(), nullable=True),
    sa.Column('cargo_class', sa.Integer(), nullable=True),
    sa.Column('danger', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etsng_code'), 'etsng', ['code'], unique=False)
    op.create_index(op.f('ix_etsng_id'), 'etsng', ['id'], unique=False)
    op.create_index(op.f('ix_etsng_name'), 'etsng', ['name'], unique=False)
    op.create_table('gng',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('code_etsng', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gng_code'), 'gng', ['code'], unique=False)
    op.create_index(op.f('ix_gng_id'), 'gng', ['id'], unique=False)
    op.create_index(op.f('ix_gng_name'), 'gng', ['name'], unique=False)
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_type_id'), 'service_type', ['id'], unique=False)
    op.create_index(op.f('ix_service_type_name'), 'service_type', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), server_default='0', nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_id'), 'vat', ['id'], unique=False)
    op.create_index(op.f('ix_vat_name'), 'vat', ['name'], unique=False)
    op.create_table('wagon_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wagon_type_id'), 'wagon_type', ['id'], unique=False)
    op.create_index(op.f('ix_wagon_type_name'), 'wagon_type', ['name'], unique=False)
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=12), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_bin_iin'), 'contractor', ['bin_iin'], unique=False)
    op.create_index(op.f('ix_contractor_country_id'), 'contractor', ['country_id'], unique=False)
    op.create_index(op.f('ix_contractor_id'), 'contractor', ['id'], unique=False)
    op.create_index(op.f('ix_contractor_legal_address'), 'contractor', ['legal_address'], unique=False)
    op.create_index(op.f('ix_contractor_legal_address_eng'), 'contractor', ['legal_address_eng'], unique=False)
    op.create_index(op.f('ix_contractor_name'), 'contractor', ['name'], unique=False)
    op.create_table('operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('is_tariff', sa.Boolean(), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_id'), 'operation', ['id'], unique=False)
    op.create_index(op.f('ix_operation_name'), 'operation', ['name'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=25), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_bin_iin'), 'organization', ['bin_iin'], unique=False)
    op.create_index(op.f('ix_organization_country_id'), 'organization', ['country_id'], unique=False)
    op.create_index(op.f('ix_organization_full_name'), 'organization', ['full_name'], unique=False)
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    op.create_index(op.f('ix_organization_legal_address'), 'organization', ['legal_address'], unique=False)
    op.create_index(op.f('ix_organization_legal_address_eng'), 'organization', ['legal_address_eng'], unique=False)
    op.create_index(op.f('ix_organization_name'), 'organization', ['name'], unique=False)
    op.create_table('territory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territory_code'), 'territory', ['code'], unique=False)
    op.create_index(op.f('ix_territory_id'), 'territory', ['id'], unique=False)
    op.create_index(op.f('ix_territory_name'), 'territory', ['name'], unique=False)
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=34), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_bik', sa.String(length=11), nullable=True),
    sa.Column('bank_cor_name', sa.String(length=200), nullable=True),
    sa.Column('bank_cor_bik', sa.String(length=11), nullable=True),
    sa.Column('bank_cor_acc', sa.String(length=34), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_account_contractor_id'), 'bank_account', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_bank_account_currency_id'), 'bank_account', ['currency_id'], unique=False)
    op.create_index(op.f('ix_bank_account_id'), 'bank_account', ['id'], unique=False)
    op.create_index(op.f('ix_bank_account_name'), 'bank_account', ['name'], unique=False)
    op.create_index(op.f('ix_bank_account_organization_id'), 'bank_account', ['organization_id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('number', sa.String(length=150), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_contractor_id'), 'contract', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_contract_currency_id'), 'contract', ['currency_id'], unique=False)
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=False)
    op.create_index(op.f('ix_contract_name'), 'contract', ['name'], unique=False)
    op.create_index(op.f('ix_contract_organization_id'), 'contract', ['organization_id'], unique=False)
    op.create_table('railway_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=True),
    sa.Column('is_transit', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=10), nullable=True),
    sa.Column('first_number', sa.Integer(), nullable=True),
    sa.Column('is_one_code', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_code_code'), 'railway_code', ['code'], unique=False)
    op.create_index(op.f('ix_railway_code_id'), 'railway_code', ['id'], unique=False)
    op.create_index(op.f('ix_railway_code_name'), 'railway_code', ['name'], unique=False)
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('paragraphs', sa.String(length=50), nullable=True),
    sa.Column('tech_pd', sa.String(length=100), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territory.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_code'), 'station', ['code'], unique=False)
    op.create_index(op.f('ix_station_id'), 'station', ['id'], unique=False)
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=False)
    op.create_table('dislocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('wagon', sa.String(length=50), nullable=False),
    sa.Column('container', sa.String(length=50), nullable=False),
    sa.Column('container_type', sa.String(length=50), nullable=False),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('is_broken', sa.Boolean(), nullable=False),
    sa.Column('nomer_nakladnoi', sa.String(length=100), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('arrive_date_real', sa.Date(), nullable=True),
    sa.Column('current_position_date', sa.Date(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_end', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('full_distance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gruz_sender', sa.String(length=255), nullable=True),
    sa.Column('gruz_receiver', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('days_wo_movement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('days_wo_operation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('send_date_time', sa.DateTime(), nullable=True),
    sa.Column('days_in_transit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('arrived', sa.Boolean(), nullable=True),
    sa.Column('round_vagon', sa.Boolean(), nullable=True),
    sa.Column('vagon_comment', sa.String(length=255), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('days_end', sa.String(length=255), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('current_station_id', sa.Integer(), nullable=True),
    sa.Column('etsng_id', sa.Integer(), nullable=True),
    sa.Column('previous_etsng_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['etsng_id'], ['etsng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_etsng_id'], ['etsng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dislocation_arrive_date_real'), 'dislocation', ['arrive_date_real'], unique=False)
    op.create_index(op.f('ix_dislocation_container'), 'dislocation', ['container'], unique=False)
    op.create_index(op.f('ix_dislocation_container_type'), 'dislocation', ['container_type'], unique=False)
    op.create_index(op.f('ix_dislocation_current_position_date'), 'dislocation', ['current_position_date'], unique=False)
    op.create_index(op.f('ix_dislocation_current_station_id'), 'dislocation', ['current_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_date'), 'dislocation', ['date'], unique=False)
    op.create_index(op.f('ix_dislocation_eta'), 'dislocation', ['eta'], unique=False)
    op.create_index(op.f('ix_dislocation_etsng_id'), 'dislocation', ['etsng_id'], unique=False)
    op.create_index(op.f('ix_dislocation_from_station_id'), 'dislocation', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_gruz_receiver'), 'dislocation', ['gruz_receiver'], unique=False)
    op.create_index(op.f('ix_dislocation_gruz_sender'), 'dislocation', ['gruz_sender'], unique=False)
    op.create_index(op.f('ix_dislocation_id'), 'dislocation', ['id'], unique=False)
    op.create_index(op.f('ix_dislocation_nomer_nakladnoi'), 'dislocation', ['nomer_nakladnoi'], unique=False)
    op.create_index(op.f('ix_dislocation_operation'), 'dislocation', ['operation'], unique=False)
    op.create_index(op.f('ix_dislocation_owner'), 'dislocation', ['owner'], unique=False)
    op.create_index(op.f('ix_dislocation_previous_etsng_id'), 'dislocation', ['previous_etsng_id'], unique=False)
    op.create_index(op.f('ix_dislocation_send_date'), 'dislocation', ['send_date'], unique=False)
    op.create_index(op.f('ix_dislocation_send_date_time'), 'dislocation', ['send_date_time'], unique=False)
    op.create_index(op.f('ix_dislocation_to_station_id'), 'dislocation', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_wagon'), 'dislocation', ['wagon'], unique=False)
    op.create_table('expense_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('tech_pd', sa.String(length=100), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('summ', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_registration_date'), 'expense_registration', ['date'], unique=False)
    op.create_index(op.f('ix_expense_registration_id'), 'expense_registration', ['id'], unique=False)
    op.create_index(op.f('ix_expense_registration_number'), 'expense_registration', ['number'], unique=False)
    op.create_index(op.f('ix_expense_registration_organization_id'), 'expense_registration', ['organization_id'], unique=False)
    op.create_table('railway_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('summ', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_order_author_id'), 'railway_order', ['author_id'], unique=False)
    op.create_index(op.f('ix_railway_order_bank_account_id'), 'railway_order', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_railway_order_contract_id'), 'railway_order', ['contract_id'], unique=False)
    op.create_index(op.f('ix_railway_order_contractor_id'), 'railway_order', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_railway_order_currency_id'), 'railway_order', ['currency_id'], unique=False)
    op.create_index(op.f('ix_railway_order_date'), 'railway_order', ['date'], unique=False)
    op.create_index(op.f('ix_railway_order_id'), 'railway_order', ['id'], unique=False)
    op.create_index(op.f('ix_railway_order_manager_id'), 'railway_order', ['manager_id'], unique=False)
    op.create_index(op.f('ix_railway_order_number'), 'railway_order', ['number'], unique=False)
    op.create_index(op.f('ix_railway_order_order_number'), 'railway_order', ['order_number'], unique=False)
    op.create_index(op.f('ix_railway_order_organization_id'), 'railway_order', ['organization_id'], unique=False)
    op.create_index(op.f('ix_railway_order_service_type_id'), 'railway_order', ['service_type_id'], unique=False)
    op.create_table('railway_subcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['railway_code.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_subcode_id'), 'railway_subcode', ['id'], unique=False)
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('weight', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('profit', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('wagon_type_id', sa.Integer(), nullable=False),
    sa.Column('etsng_id', sa.Integer(), nullable=True),
    sa.Column('gng_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['etsng_id'], ['etsng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gng_id'], ['gng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['wagon_type_id'], ['wagon_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_author_id'), 'specification', ['author_id'], unique=False)
    op.create_index(op.f('ix_specification_contract_id'), 'specification', ['contract_id'], unique=False)
    op.create_index(op.f('ix_specification_contractor_id'), 'specification', ['contractor_id'], unique=False)
    op.create_index(op.f('ix_specification_currency_id'), 'specification', ['currency_id'], unique=False)
    op.create_index(op.f('ix_specification_date'), 'specification', ['date'], unique=False)
    op.create_index(op.f('ix_specification_etsng_id'), 'specification', ['etsng_id'], unique=False)
    op.create_index(op.f('ix_specification_from_station_id'), 'specification', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_specification_gng_id'), 'specification', ['gng_id'], unique=False)
    op.create_index(op.f('ix_specification_id'), 'specification', ['id'], unique=False)
    op.create_index(op.f('ix_specification_number'), 'specification', ['number'], unique=False)
    op.create_index(op.f('ix_specification_organization_id'), 'specification', ['organization_id'], unique=False)
    op.create_index(op.f('ix_specification_to_station_id'), 'specification', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_specification_wagon_type_id'), 'specification', ['wagon_type_id'], unique=False)
    op.create_table('railway_order_way',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('summ', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['railway_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_order_way_id'), 'railway_order_way', ['id'], unique=False)
    op.create_index(op.f('ix_railway_order_way_line_number'), 'railway_order_way', ['line_number'], unique=False)
    op.create_index(op.f('ix_railway_order_way_order_id'), 'railway_order_way', ['order_id'], unique=False)
    op.create_index(op.f('ix_railway_order_way_specification_id'), 'railway_order_way', ['specification_id'], unique=False)
    op.create_table('railway_route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('weight', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('profit_plan', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('profit_fact', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('wagon', sa.String(length=20), nullable=True),
    sa.Column('wagon2', sa.String(length=20), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_from_sng', sa.Date(), nullable=True),
    sa.Column('date_reload', sa.Date(), nullable=True),
    sa.Column('date_arrive', sa.Date(), nullable=True),
    sa.Column('date_border', sa.Date(), nullable=True),
    sa.Column('nomer_nakladnoi', sa.String(length=100), nullable=True),
    sa.Column('td', sa.String(length=100), nullable=True),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('gng_id', sa.Integer(), nullable=True),
    sa.Column('etsng_id', sa.Integer(), nullable=True),
    sa.Column('wagon_type_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['etsng_id'], ['etsng.id'], ),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['gng_id'], ['gng.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['railway_order.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ),
    sa.ForeignKeyConstraint(['wagon_type_id'], ['wagon_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_route_container'), 'railway_route', ['container'], unique=False)
    op.create_index(op.f('ix_railway_route_date_arrive'), 'railway_route', ['date_arrive'], unique=False)
    op.create_index(op.f('ix_railway_route_date_border'), 'railway_route', ['date_border'], unique=False)
    op.create_index(op.f('ix_railway_route_date_from'), 'railway_route', ['date_from'], unique=False)
    op.create_index(op.f('ix_railway_route_date_from_sng'), 'railway_route', ['date_from_sng'], unique=False)
    op.create_index(op.f('ix_railway_route_date_reload'), 'railway_route', ['date_reload'], unique=False)
    op.create_index(op.f('ix_railway_route_etsng_id'), 'railway_route', ['etsng_id'], unique=False)
    op.create_index(op.f('ix_railway_route_from_station_id'), 'railway_route', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_railway_route_gng_id'), 'railway_route', ['gng_id'], unique=False)
    op.create_index(op.f('ix_railway_route_id'), 'railway_route', ['id'], unique=False)
    op.create_index(op.f('ix_railway_route_nomer_nakladnoi'), 'railway_route', ['nomer_nakladnoi'], unique=False)
    op.create_index(op.f('ix_railway_route_order_id'), 'railway_route', ['order_id'], unique=False)
    op.create_index(op.f('ix_railway_route_to_station_id'), 'railway_route', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_railway_route_wagon'), 'railway_route', ['wagon'], unique=False)
    op.create_index(op.f('ix_railway_route_wagon2'), 'railway_route', ['wagon2'], unique=False)
    op.create_index(op.f('ix_railway_route_wagon_type_id'), 'railway_route', ['wagon_type_id'], unique=False)
    op.create_table('specification_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('vat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['specification_id'], ['specification.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_expense_contract_id'), 'specification_expense', ['contract_id'], unique=False)
    op.create_index(op.f('ix_specification_expense_currency_id'), 'specification_expense', ['currency_id'], unique=False)
    op.create_index(op.f('ix_specification_expense_id'), 'specification_expense', ['id'], unique=False)
    op.create_index(op.f('ix_specification_expense_line_number'), 'specification_expense', ['line_number'], unique=False)
    op.create_index(op.f('ix_specification_expense_operation_id'), 'specification_expense', ['operation_id'], unique=False)
    op.create_index(op.f('ix_specification_expense_provider_id'), 'specification_expense', ['provider_id'], unique=False)
    op.create_index(op.f('ix_specification_expense_specification_id'), 'specification_expense', ['specification_id'], unique=False)
    op.create_index(op.f('ix_specification_expense_vat_id'), 'specification_expense', ['vat_id'], unique=False)
    op.create_table('railway_route_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('rate', sa.Numeric(precision=15, scale=4), server_default='0', nullable=False),
    sa.Column('railway_route_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('vat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['contractor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['railway_route_id'], ['railway_route.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_route_expense_contract_id'), 'railway_route_expense', ['contract_id'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_currency_id'), 'railway_route_expense', ['currency_id'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_id'), 'railway_route_expense', ['id'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_line_number'), 'railway_route_expense', ['line_number'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_operation_id'), 'railway_route_expense', ['operation_id'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_provider_id'), 'railway_route_expense', ['provider_id'], unique=False)
    op.create_index(op.f('ix_railway_route_expense_railway_route_id'), 'railway_route_expense', ['railway_route_id'], unique=False)
    op.create_table('specification_expense_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('price', sa.Numeric(precision=15, scale=2), server_default='0', nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('wagon', sa.String(length=20), nullable=True),
    sa.Column('container', sa.String(length=20), nullable=True),
    sa.Column('nomer_nakladnoi', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('td', sa.String(length=200), nullable=True),
    sa.Column('expense_registration_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('vat_id', sa.Integer(), nullable=True),
    sa.Column('railway_route_expense_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expense_registration_id'], ['expense_registration.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['railway_route_expense_id'], ['railway_route_expense.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vat_id'], ['vat.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specification_expense_line_id'), 'specification_expense_line', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_specification_expense_line_id'), table_name='specification_expense_line')
    op.drop_table('specification_expense_line')
    op.drop_index(op.f('ix_railway_route_expense_railway_route_id'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_provider_id'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_operation_id'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_line_number'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_id'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_currency_id'), table_name='railway_route_expense')
    op.drop_index(op.f('ix_railway_route_expense_contract_id'), table_name='railway_route_expense')
    op.drop_table('railway_route_expense')
    op.drop_index(op.f('ix_specification_expense_vat_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_specification_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_provider_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_operation_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_line_number'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_currency_id'), table_name='specification_expense')
    op.drop_index(op.f('ix_specification_expense_contract_id'), table_name='specification_expense')
    op.drop_table('specification_expense')
    op.drop_index(op.f('ix_railway_route_wagon_type_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_wagon2'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_wagon'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_to_station_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_order_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_nomer_nakladnoi'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_gng_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_from_station_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_etsng_id'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_date_reload'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_date_from_sng'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_date_from'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_date_border'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_date_arrive'), table_name='railway_route')
    op.drop_index(op.f('ix_railway_route_container'), table_name='railway_route')
    op.drop_table('railway_route')
    op.drop_index(op.f('ix_railway_order_way_specification_id'), table_name='railway_order_way')
    op.drop_index(op.f('ix_railway_order_way_order_id'), table_name='railway_order_way')
    op.drop_index(op.f('ix_railway_order_way_line_number'), table_name='railway_order_way')
    op.drop_index(op.f('ix_railway_order_way_id'), table_name='railway_order_way')
    op.drop_table('railway_order_way')
    op.drop_index(op.f('ix_specification_wagon_type_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_to_station_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_organization_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_number'), table_name='specification')
    op.drop_index(op.f('ix_specification_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_gng_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_from_station_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_etsng_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_date'), table_name='specification')
    op.drop_index(op.f('ix_specification_currency_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_contractor_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_contract_id'), table_name='specification')
    op.drop_index(op.f('ix_specification_author_id'), table_name='specification')
    op.drop_table('specification')
    op.drop_index(op.f('ix_railway_subcode_id'), table_name='railway_subcode')
    op.drop_table('railway_subcode')
    op.drop_index(op.f('ix_railway_order_service_type_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_organization_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_order_number'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_number'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_manager_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_date'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_currency_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_contractor_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_contract_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_bank_account_id'), table_name='railway_order')
    op.drop_index(op.f('ix_railway_order_author_id'), table_name='railway_order')
    op.drop_table('railway_order')
    op.drop_index(op.f('ix_expense_registration_organization_id'), table_name='expense_registration')
    op.drop_index(op.f('ix_expense_registration_number'), table_name='expense_registration')
    op.drop_index(op.f('ix_expense_registration_id'), table_name='expense_registration')
    op.drop_index(op.f('ix_expense_registration_date'), table_name='expense_registration')
    op.drop_table('expense_registration')
    op.drop_index(op.f('ix_dislocation_wagon'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_to_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_send_date_time'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_send_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_previous_etsng_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_owner'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_operation'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_nomer_nakladnoi'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_gruz_sender'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_gruz_receiver'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_from_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_etsng_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_eta'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_current_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_current_position_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_container_type'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_container'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_arrive_date_real'), table_name='dislocation')
    op.drop_table('dislocation')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_index(op.f('ix_station_id'), table_name='station')
    op.drop_index(op.f('ix_station_code'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_railway_code_name'), table_name='railway_code')
    op.drop_index(op.f('ix_railway_code_id'), table_name='railway_code')
    op.drop_index(op.f('ix_railway_code_code'), table_name='railway_code')
    op.drop_table('railway_code')
    op.drop_index(op.f('ix_contract_organization_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_currency_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_contractor_id'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_bank_account_organization_id'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_name'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_id'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_currency_id'), table_name='bank_account')
    op.drop_index(op.f('ix_bank_account_contractor_id'), table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index(op.f('ix_territory_name'), table_name='territory')
    op.drop_index(op.f('ix_territory_id'), table_name='territory')
    op.drop_index(op.f('ix_territory_code'), table_name='territory')
    op.drop_table('territory')
    op.drop_index(op.f('ix_organization_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_legal_address_eng'), table_name='organization')
    op.drop_index(op.f('ix_organization_legal_address'), table_name='organization')
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_full_name'), table_name='organization')
    op.drop_index(op.f('ix_organization_country_id'), table_name='organization')
    op.drop_index(op.f('ix_organization_bin_iin'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_operation_name'), table_name='operation')
    op.drop_index(op.f('ix_operation_id'), table_name='operation')
    op.drop_table('operation')
    op.drop_index(op.f('ix_contractor_name'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_legal_address_eng'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_legal_address'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_id'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_country_id'), table_name='contractor')
    op.drop_index(op.f('ix_contractor_bin_iin'), table_name='contractor')
    op.drop_table('contractor')
    op.drop_index(op.f('ix_wagon_type_name'), table_name='wagon_type')
    op.drop_index(op.f('ix_wagon_type_id'), table_name='wagon_type')
    op.drop_table('wagon_type')
    op.drop_index(op.f('ix_vat_name'), table_name='vat')
    op.drop_index(op.f('ix_vat_id'), table_name='vat')
    op.drop_table('vat')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_type_name'), table_name='service_type')
    op.drop_index(op.f('ix_service_type_id'), table_name='service_type')
    op.drop_table('service_type')
    op.drop_index(op.f('ix_gng_name'), table_name='gng')
    op.drop_index(op.f('ix_gng_id'), table_name='gng')
    op.drop_index(op.f('ix_gng_code'), table_name='gng')
    op.drop_table('gng')
    op.drop_index(op.f('ix_etsng_name'), table_name='etsng')
    op.drop_index(op.f('ix_etsng_id'), table_name='etsng')
    op.drop_index(op.f('ix_etsng_code'), table_name='etsng')
    op.drop_table('etsng')
    op.drop_index(op.f('ix_currency_name'), table_name='currency')
    op.drop_index(op.f('ix_currency_id'), table_name='currency')
    op.drop_index(op.f('ix_currency_code'), table_name='currency')
    op.drop_table('currency')
    op.drop_index(op.f('ix_country_name'), table_name='country')
    op.drop_index(op.f('ix_country_id'), table_name='country')
    op.drop_index(op.f('ix_country_code_iso'), table_name='country')
    op.drop_index(op.f('ix_country_code_alpha2'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
