"""init

Revision ID: a8096446804d
Revises: a9cc27b81908
Create Date: 2025-12-04 16:22:39.856669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8096446804d'
down_revision: Union[str, Sequence[str], None] = 'a9cc27b81908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('wagon', sa.String(length=50), nullable=False),
    sa.Column('container', sa.String(length=50), nullable=False),
    sa.Column('is_empty', sa.Boolean(), nullable=False),
    sa.Column('is_broken', sa.Boolean(), nullable=False),
    sa.Column('nomer_nakladnoi', sa.String(length=100), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('arrive_date_real', sa.Date(), nullable=True),
    sa.Column('current_position_date', sa.Date(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_end', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('full_distance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gruz_sender', sa.String(length=255), nullable=True),
    sa.Column('gruz_receiver', sa.String(length=255), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('days_wo_movement', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('days_wo_operation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('send_date_time', sa.DateTime(), nullable=True),
    sa.Column('days_in_transit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('arrived', sa.Boolean(), nullable=True),
    sa.Column('round_vagon', sa.Boolean(), nullable=True),
    sa.Column('vagon_comment', sa.String(length=255), nullable=True),
    sa.Column('operation_id', sa.String(length=255), nullable=True),
    sa.Column('days_end', sa.String(length=255), nullable=True),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('current_station_id', sa.Integer(), nullable=True),
    sa.Column('etsng_id', sa.Integer(), nullable=True),
    sa.Column('previous_etsng_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['etsng_id'], ['etsng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_etsng_id'], ['etsng.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_station_id'], ['station.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dislocation_arrive_date_real'), 'dislocation', ['arrive_date_real'], unique=False)
    op.create_index(op.f('ix_dislocation_container'), 'dislocation', ['container'], unique=False)
    op.create_index(op.f('ix_dislocation_current_position_date'), 'dislocation', ['current_position_date'], unique=False)
    op.create_index(op.f('ix_dislocation_current_station_id'), 'dislocation', ['current_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_date'), 'dislocation', ['date'], unique=False)
    op.create_index(op.f('ix_dislocation_eta'), 'dislocation', ['eta'], unique=False)
    op.create_index(op.f('ix_dislocation_etsng_id'), 'dislocation', ['etsng_id'], unique=False)
    op.create_index(op.f('ix_dislocation_from_station_id'), 'dislocation', ['from_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_gruz_receiver'), 'dislocation', ['gruz_receiver'], unique=False)
    op.create_index(op.f('ix_dislocation_gruz_sender'), 'dislocation', ['gruz_sender'], unique=False)
    op.create_index(op.f('ix_dislocation_id'), 'dislocation', ['id'], unique=False)
    op.create_index(op.f('ix_dislocation_nomer_nakladnoi'), 'dislocation', ['nomer_nakladnoi'], unique=False)
    op.create_index(op.f('ix_dislocation_operation'), 'dislocation', ['operation'], unique=False)
    op.create_index(op.f('ix_dislocation_owner'), 'dislocation', ['owner'], unique=False)
    op.create_index(op.f('ix_dislocation_previous_etsng_id'), 'dislocation', ['previous_etsng_id'], unique=False)
    op.create_index(op.f('ix_dislocation_send_date'), 'dislocation', ['send_date'], unique=False)
    op.create_index(op.f('ix_dislocation_send_date_time'), 'dislocation', ['send_date_time'], unique=False)
    op.create_index(op.f('ix_dislocation_to_station_id'), 'dislocation', ['to_station_id'], unique=False)
    op.create_index(op.f('ix_dislocation_wagon'), 'dislocation', ['wagon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dislocation_wagon'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_to_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_send_date_time'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_send_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_previous_etsng_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_owner'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_operation'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_nomer_nakladnoi'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_gruz_sender'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_gruz_receiver'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_from_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_etsng_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_eta'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_current_station_id'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_current_position_date'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_container'), table_name='dislocation')
    op.drop_index(op.f('ix_dislocation_arrive_date_real'), table_name='dislocation')
    op.drop_table('dislocation')
    # ### end Alembic commands ###
