"""init

Revision ID: aad1291c2263
Revises: 5313aac39de0
Create Date: 2025-12-10 11:24:41.329852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad1291c2263'
down_revision: Union[str, Sequence[str], None] = '5313aac39de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('railway_order_way_order_id_fkey'), 'railway_order_way', type_='foreignkey')
    op.create_foreign_key(None, 'railway_order_way', 'railway_order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('railway_route_order_id_fkey'), 'railway_route', type_='foreignkey')
    op.create_foreign_key(None, 'railway_route', 'railway_order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('railway_route_expense_railway_route_id_fkey'), 'railway_route_expense', type_='foreignkey')
    op.create_foreign_key(None, 'railway_route_expense', 'railway_route', ['railway_route_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('specification_expense_specification_id_fkey'), 'specification_expense', type_='foreignkey')
    op.create_foreign_key(None, 'specification_expense', 'specification', ['specification_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('specification_expense_line_expense_registration_id_fkey'), 'specification_expense_line', type_='foreignkey')
    op.create_foreign_key(None, 'specification_expense_line', 'expense_registration', ['expense_registration_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'specification_expense_line', type_='foreignkey')
    op.create_foreign_key(op.f('specification_expense_line_expense_registration_id_fkey'), 'specification_expense_line', 'expense_registration', ['expense_registration_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'specification_expense', type_='foreignkey')
    op.create_foreign_key(op.f('specification_expense_specification_id_fkey'), 'specification_expense', 'specification', ['specification_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'railway_route_expense', type_='foreignkey')
    op.create_foreign_key(op.f('railway_route_expense_railway_route_id_fkey'), 'railway_route_expense', 'railway_route', ['railway_route_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'railway_route', type_='foreignkey')
    op.create_foreign_key(op.f('railway_route_order_id_fkey'), 'railway_route', 'railway_order', ['order_id'], ['id'])
    op.drop_constraint(None, 'railway_order_way', type_='foreignkey')
    op.create_foreign_key(op.f('railway_order_way_order_id_fkey'), 'railway_order_way', 'railway_order', ['order_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
