"""init

Revision ID: c93220d11462
Revises: 8dde6b62f9f1
Create Date: 2025-11-28 15:39:46.928515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c93220d11462'
down_revision: Union[str, Sequence[str], None] = '8dde6b62f9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.Column('bin_iin', sa.String(length=25), nullable=True),
    sa.Column('is_legal', sa.Boolean(), nullable=True),
    sa.Column('kbe', sa.String(length=3), nullable=True),
    sa.Column('legal_address', sa.String(length=255), nullable=True),
    sa.Column('legal_address_eng', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_id'), 'organization', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_id'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
