"""init

Revision ID: f78c1fe0e582
Revises: 3a420a9918bd
Create Date: 2025-11-28 12:43:53.508946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78c1fe0e582'
down_revision: Union[str, Sequence[str], None] = '3a420a9918bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('guid_1c', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_id'), 'vat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vat_id'), table_name='vat')
    op.drop_table('vat')
    # ### end Alembic commands ###
